export enum ContentType {
    JSON = "application/json",
    XML = "application/xml",
    HTML = "text/html",
    PLAIN_TEXT = "text/plain",
    FORM_URLENCODED = "application/x-www-form-urlencoded",
    MULTIPART_FORM_DATA = "multipart/form-data",
    JAVASCRIPT = "application/javascript",
    CSS = "text/css",
    CSV = "text/csv",
    PDF = "application/pdf",
    ZIP = "application/zip",
    GZIP = "application/gzip",
    JPEG = "image/jpeg",
    PNG = "image/png",
    GIF = "image/gif",
    SVG = "image/svg+xml",
    WEBP = "image/webp",
    OCTET_STREAM = "application/octet-stream",
    RDF_XML = "application/rdf+xml",
    ATOM_XML = "application/atom+xml",
    RSS_XML = "application/rss+xml",
}
